# Task 1 Data Cleaning and Processing

In [2]:
print("Hello World!")

Hello World!

In [3]:
import pandas as pd

In [4]:
import numpy as np

Import data file

In [30]:
df = pd.read_csv("data/student_performance.csv")

In [42]:
df

,Student_ID,Student_Name,Age,Gender,City,Subject,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Test1_Score,Test2_Score,Final_Exam_Score,Previous_Percentage,Parent_Education,Internet_Access,Extracurricular
0,10387,Kabir_387,15.0,Female,Jodhpur,Science,13.0,55.6,46.0,89.0,54.0,35.0,70.0,Graduate,Yes,Yes
1,10487,Aditya_487,19.0,Male,Jaipur,English,34.6,82.6,56.0,65.0,73.0,44.0,63.0,10Th,Yes,Yes
2,10134,Priya_134,19.0,Female,Alwar,Science,18.2,55.2,86.0,93.0,92.0,57.0,105.0,12Th,No,Yes
3,10470,Sneha_470,19.0,Female,Jodhpur,Mathematics,8.8,57.9,48.0,89.0,90.0,97.0,61.4,Graduate,Yes,No
4,10110,Kunal_110,17.0,Female,Jodhpur,Science,12.1,79.0,73.0,31.0,95.0,44.0,95.3,10Th,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,10078,Vivaan_78,19.0,Female,Kota,Computer Science,5.1,96.5,76.0,85.0,35.0,52.0,71.8,Graduate,Yes,No
504,10441,Aditya_441,19.0,Female,Bikaner,Social Science,12.9,81.1,46.0,50.0,74.0,68.0,72.2,Graduate,No,Yes
505,10283,Kavya_283,18.0,Female,Ajmer,Social Science,21.1,65.3,39.0,51.0,52.0,57.0,83.2,12Th,Yes,No
506,10391,Aarav_391,16.0,Female,Kota,English,27.1,98.3,42.0,31.0,30.0,85.0,71.9,12Th,Yes,No
507,10258,Kabir_258,15.0,Male,Ajmer,Computer Science,29.0,77.6,62.0,48.0,34.0,96.0,91.1,12Th,Yes,Yes

In [7]:
print(df.columns)

Index(['Student_ID', 'Student_Name', 'Age', 'Gender', 'City', 'Subject',
       'Study_Hours_Per_Week', 'Attendance_Percentage', 'Assignment_Score',
       'Test1_Score', 'Test2_Score', 'Final_Exam_Score', 'Previous_Percentage',
       'Parent_Education', 'Internet_Access', 'Extracurricular'],
      dtype='str')

In [8]:
df.columns[1]

'Student_Name'

In [9]:
print(df.dtypes)

Student_ID                 int64
Student_Name                 str
Age                      float64
Gender                       str
City                         str
Subject                      str
Study_Hours_Per_Week     float64
Attendance_Percentage    float64
Assignment_Score         float64
Test1_Score              float64
Test2_Score              float64
Final_Exam_Score         float64
Previous_Percentage      float64
Parent_Education             str
Internet_Access              str
Extracurricular              str
dtype: object

Duplicate Rows removed

In [10]:
print(df.duplicated().sum())

8

In [11]:
df = df.drop_duplicates()

In [12]:
print(df.duplicated().sum())

0

Null Value find and fill

In [40]:
print(df.isnull().sum())

Student_ID               0
Student_Name             0
Age                      4
Gender                   0
City                     4
Subject                  0
Study_Hours_Per_Week     4
Attendance_Percentage    4
Assignment_Score         3
Test1_Score              3
Test2_Score              3
Final_Exam_Score         3
Previous_Percentage      3
Parent_Education         4
Internet_Access          0
Extracurricular          0
dtype: int64

In [41]:
# Numerical columns
numeric_cols = [
    "Age",
    "Study_Hours_Per_Week",
    "Attendance_Percentage",
    "Assignment_Score",
    "Test1_Score",
    "Test2_Score",
    "Final_Exam_Score",
    "Previous_Percentage",
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

# Categorical column
df["City"] = df["City"].fillna(df["City"].mode()[0])
df["Parent_Education"]=df["Parent_Education"].fillna(df["Parent_Education"].mode()[0])

In [15]:
print(df.isnull().sum())

Student_ID               0
Student_Name             0
Age                      0
Gender                   0
City                     0
Subject                  0
Study_Hours_Per_Week     0
Attendance_Percentage    0
Assignment_Score         0
Test1_Score              0
Test2_Score              0
Final_Exam_Score         0
Previous_Percentage      0
Parent_Education         0
Internet_Access          0
Extracurricular          0
dtype: int64

In [16]:
df.head(5)

,Student_ID,Student_Name,Age,Gender,City,Subject,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Test1_Score,Test2_Score,Final_Exam_Score,Previous_Percentage,Parent_Education,Internet_Access,Extracurricular
0,10387,Kabir_387,15.0,Female,Jodhpur,Science,13.0,55.6,46.0,89.0,54.0,35.0,70.0,Graduate,Yes,Yes
1,10487,Aditya_487,19.0,Male,Jaipur,English,34.6,82.6,56.0,65.0,73.0,44.0,63.0,10th,Yes,Yes
2,10134,Priya_134,19.0,Female,Alwar,Science,18.2,55.2,86.0,93.0,92.0,57.0,105.0,12th,No,Yes
3,10470,Sneha_470,19.0,Female,Jodhpur,Mathematics,8.8,57.9,48.0,89.0,90.0,97.0,61.4,Graduate,Yes,No
4,10110,Kunal_110,17.0,Female,Jodhpur,Science,12.1,79.0,73.0,31.0,95.0,44.0,95.3,10th,Yes,No

In [17]:
df["Student_Name"] = df["Student_Name"].str.strip()

In [18]:
df["Student_Name"]

0       Kabir_387
1      Aditya_487
2       Priya_134
3       Sneha_470
4       Kunal_110
          ...
503     Vivaan_78
504    Aditya_441
505     Kavya_283
506     Aarav_391
507     Kabir_258
Name: Student_Name, Length: 500, dtype: str

In [19]:
df["Student_Name"].is_unique

True

In [20]:
df["Age"] = df["Age"].astype(int)

In [21]:
df["Age"].dtype

dtype('int64')

In [22]:
df["Age"]

0      15
1      19
2      19
3      19
4      17
       ..
503    19
504    19
505    18
506    16
507    15
Name: Age, Length: 500, dtype: int64

In [26]:
text_cols = ["Gender", "City", "Subject"]

for col in text_cols:
    df[col] = df[col].str.strip().str.title()

In [27]:
for col in text_cols:
    print(col)
    print(df[col].unique())

Gender
<StringArray>
['Female', 'Male', 'M']
Length: 3, dtype: str
City
<StringArray>
['Jodhpur', 'Jaipur', 'Alwar', 'Udaipur', 'Ajmer', 'Bikaner', 'Kota', 'Delhi']
Length: 8, dtype: str
Subject
<StringArray>
['Science', 'English', 'Mathematics', 'Social Science', 'Computer Science']
Length: 5, dtype: str

In [29]:
df.head()

,Student_ID,Student_Name,Age,Gender,City,Subject,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Test1_Score,Test2_Score,Final_Exam_Score,Previous_Percentage,Parent_Education,Internet_Access,Extracurricular
0,10387,Kabir_387,15,Female,Jodhpur,Science,13.0,55.6,46.0,89.0,54.0,35.0,70.0,Graduate,Yes,Yes
1,10487,Aditya_487,19,Male,Jaipur,English,34.6,82.6,56.0,65.0,73.0,44.0,63.0,10th,Yes,Yes
2,10134,Priya_134,19,Female,Alwar,Science,18.2,55.2,86.0,93.0,92.0,57.0,105.0,12th,No,Yes
3,10470,Sneha_470,19,Female,Jodhpur,Mathematics,8.8,57.9,48.0,89.0,90.0,97.0,61.4,Graduate,Yes,No
4,10110,Kunal_110,17,Female,Jodhpur,Science,12.1,79.0,73.0,31.0,95.0,44.0,95.3,10th,Yes,No

In [33]:
df["Parent_Education"] = (
    df["Parent_Education"]
    .str.strip()
    .str.title()
)

In [34]:
df['Parent_Education']

0      Graduate
1          10Th
2          12Th
3      Graduate
4          10Th
         ...
503    Graduate
504    Graduate
505        12Th
506        12Th
507        12Th
Name: Parent_Education, Length: 508, dtype: str

In [38]:
df.to_csv("data/student_performance_cleaned.csv", index=False)

In [39]:
df

,Student_ID,Student_Name,Age,Gender,City,Subject,Study_Hours_Per_Week,Attendance_Percentage,Assignment_Score,Test1_Score,Test2_Score,Final_Exam_Score,Previous_Percentage,Parent_Education,Internet_Access,Extracurricular
0,10387,Kabir_387,15.0,Female,Jodhpur,Science,13.0,55.6,46.0,89.0,54.0,35.0,70.0,Graduate,Yes,Yes
1,10487,Aditya_487,19.0,Male,Jaipur,English,34.6,82.6,56.0,65.0,73.0,44.0,63.0,10Th,Yes,Yes
2,10134,Priya_134,19.0,Female,Alwar,Science,18.2,55.2,86.0,93.0,92.0,57.0,105.0,12Th,No,Yes
3,10470,Sneha_470,19.0,Female,Jodhpur,Mathematics,8.8,57.9,48.0,89.0,90.0,97.0,61.4,Graduate,Yes,No
4,10110,Kunal_110,17.0,Female,Jodhpur,Science,12.1,79.0,73.0,31.0,95.0,44.0,95.3,10Th,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503,10078,Vivaan_78,19.0,Female,Kota,Computer Science,5.1,96.5,76.0,85.0,35.0,52.0,71.8,Graduate,Yes,No
504,10441,Aditya_441,19.0,Female,Bikaner,Social Science,12.9,81.1,46.0,50.0,74.0,68.0,72.2,Graduate,No,Yes
505,10283,Kavya_283,18.0,Female,Ajmer,Social Science,21.1,65.3,39.0,51.0,52.0,57.0,83.2,12Th,Yes,No
506,10391,Aarav_391,16.0,Female,Kota,English,27.1,98.3,42.0,31.0,30.0,85.0,71.9,12Th,Yes,No
507,10258,Kabir_258,15.0,Male,Ajmer,Computer Science,29.0,77.6,62.0,48.0,34.0,96.0,91.1,12Th,Yes,Yes